version: "3.9"

services:
  cli:
    image: booster_drupal/cli
    build: services/cli
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
      - XDEBUG_CONFIG=client_host=${DOCKSAL_HOST_IP} client_port=9000
      - XDEBUG_MODE
      - SIMPLETEST_BASE_URL=http://${VIRTUAL_HOST}/
      - STORYBOOK_SERVER_URL=http://${VIRTUAL_HOST}/storybook/stories/render
      - SITE_ENVIRONMENT
      - MYSQL_PORT
      - OPENAI_API_KEY
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
